- name: Install powerline
  pip: 
    executable: pip3
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages.pip }}"

- name: Find python package location
  shell: echo $(pip3 show powerline-status |grep Location|cut -d ' ' -f 2)
  register: python_package
  run_once: true

- name: Set powerline bindings location
  set_fact:
    powerline_bindings_path={{ python_package.stdout }}/powerline/bindings/bash/powerline.sh

- name: Create bash settings
  template: 
    src: bashrc_osx.j2
    dest: "{{ home_dir }}/.bashrc"
    owner: "{{ ansible_user_id }}"
    mode: u=rw,g=r,o=r