---  
  - name: Load Mac OSX specific variables
    include_vars: macos.yml
    when: ansible_os_family == "Darwin"
  
  - include_tasks: docker_bash_completion.yml

  - include_tasks: powerline.yml
    when: terminal_prompt == 'powerline'

  - include_tasks: starship.yml
    when: terminal_prompt == 'starship'
  
  - name: Install git-prompt.sh
    copy:
      src: .bash
      dest: "{{ home_dir }}/"
      owner: "{{ ansible_user_id }}"
      mode: u=rw,g=r,o=r

  - name: Create includes directory
    file:
      path: "{{ home_dir }}/.bash_includes"
      state: directory
      owner: "{{ ansible_user_id }}"
      mode: 0755
  
  - name: Copy aliases file
    copy:
      src: ".aliases"
      dest: "{{ home_dir }}/.bash_includes/aliases"
      owner: "{{ ansible_user_id }}"
      mode: u=rw,g=r,o=r

  - name: Copy shell related files to home directory
    copy:
      src: "{{ item }}"
      dest: "{{ home_dir }}/{{ item }}"
      owner: "{{ ansible_user_id }}"
      mode: u=rw,g=r,o=r
    with_items: "{{ files_to_copy }}"

  - name: Create bash settings
    template: 
      src: bashrc.j2
      dest: "{{ home_dir }}/.bashrc"
      owner: "{{ ansible_user_id }}"
      mode: u=rw,g=r,o=r
