- name: Find python package location
  shell: echo $(pip3 show powerline-status |grep Location|cut -d ' ' -f 2)
  register: python_package
  run_once: true

- name: Set powerline bindings location
  set_fact:
    powerline_bindings_path={{ python_package.stdout }}/powerline/bindings/bash/powerline.sh
    
- name: Create powerline config directory
  file:
    path: "{{ home_dir }}/{{ powerline.config.path | dirname }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    recurse: yes

- name: Copy powerline config
  copy:
    src: powerline-config.json
    dest: "{{ home_dir }}/{{ powerline.config.path }}"
    owner: "{{ ansible_user_id }}"
    mode: u=rw,g=r,o=r

- name: Copy powerline themes
  copy:
    src: themes
    dest: "{{ home_dir }}/{{ powerline.config.path | dirname }}"
    owner: "{{ ansible_user_id }}"
    mode: u=rw,g=r,o=r
